namespace RS.Fritz.Manager.API;

[MessageContract(WrapperName = "GetInfoResponse")]
public readonly record struct WanPppConnectionGetInfoResponse(
    [property: MessageBodyMember(Name = "NewEnable")] bool Enable,
    [property: MessageBodyMember(Name = "NewConnectionStatus")] string ConnectionStatus,
    [property: MessageBodyMember(Name = "NewPossibleConnectionTypes")] string PossibleConnectionTypes,
    [property: MessageBodyMember(Name = "NewConnectionType")] string ConnectionType,
    [property: MessageBodyMember(Name = "NewName")] string Name,
    [property: MessageBodyMember(Name = "NewUptime")] uint Uptime,
    [property: MessageBodyMember(Name = "NewUpstreamMaxBitRate")] uint UpstreamMaxBitRate,
    [property: MessageBodyMember(Name = "NewDownstreamMaxBitRate")] uint DownstreamMaxBitRate,
    [property: MessageBodyMember(Name = "NewLastConnectionError")] string LastConnectionError,
    [property: MessageBodyMember(Name = "NewIdleDisconnectTime")] uint IdleDisconnectTime,
    [property: MessageBodyMember(Name = "NewRSIPAvailable")] bool RsipAvailable,
    [property: MessageBodyMember(Name = "NewUserName")] string UserName,
    [property: MessageBodyMember(Name = "NewNATEnabled")] bool NatEnabled,
    [property: MessageBodyMember(Name = "NewExternalIPAddress")] string ExternalIpAddress,
    [property: MessageBodyMember(Name = "NewDNSServers")] string DnsServers,
    [property: MessageBodyMember(Name = "NewMACAddress")] string MacAddress,
    [property: MessageBodyMember(Name = "NewConnectionTrigger")] string ConnectionTrigger,
    [property: MessageBodyMember(Name = "NewLastAuthErrorInfo")] string LastAuthErrorInfo,
    [property: MessageBodyMember(Name = "NewMaxCharsUsername")] string MaxCharsUsername,
    [property: MessageBodyMember(Name = "NewMinCharsUsername")] string MinCharsUsername,
    [property: MessageBodyMember(Name = "NewAllowedCharsUsername")] string AllowedCharsUsername,
    [property: MessageBodyMember(Name = "NewMaxCharsPassword")] string MaxCharsPassword,
    [property: MessageBodyMember(Name = "NewMinCharsPassword")] string MinCharsPassword,
    [property: MessageBodyMember(Name = "NewAllowedCharsPassword")] string AllowedCharsPassword,
    [property: MessageBodyMember(Name = "NewTransportType")] string TransportType,
    [property: MessageBodyMember(Name = "NewRouteProtocolRx")] string RouteProtocolRx,
    [property: MessageBodyMember(Name = "NewPPPoEServiceName")] string PppoEServiceName,
    [property: MessageBodyMember(Name = "NewRemoteIPAddress")] string RemoteIpAddress,
    [property: MessageBodyMember(Name = "NewPPPoEACName")] string PppoEacName,
    [property: MessageBodyMember(Name = "NewDNSEnabled")] bool DnsEnabled,
    [property: MessageBodyMember(Name = "NewDNSOverrideAllowed")] bool DnsOverrideAllowed);